# Generated by Django 6.0.2 on 2026-03-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('C', 'Computer'), ('P', 'Phone'), ('T', 'Tablet')], default='C', max_length=1),
        ),
    ]
