# Generated by Django 6.0.2 on 2026-03-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_usagesession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagesession',
            options={'ordering': ['-date']},
        ),
    ]
