# Generated by Django 6.0.2 on 2026-03-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_accessory_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
