# Generated by Django 6.0.2 on 2026-03-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_device_accessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagesession',
            name='date',
            field=models.DateField(verbose_name='Usage Date'),
        ),
    ]
